spring.rabbitmq.host: rabbitmq

info:
  id: ${spring.application.name}

server:
  port: ${PORT:0}

debug: true
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
    org.springframework.security: DEBUG

    # Set DEBUG level on Hystrix to get an error message when a fallback method is used.
    com.netflix.hystrix: DEBUG

spring.sleuth.sampler.percentage: 1.0
spring.sleuth.log.json.enabled: true
