server:
  port: ${PORT:9999}

spring.cloud.stream.bindings.output.destination: reservations
hystrix.command.default.execution.isolation.strategy: THREAD

ribbon:
  ConnectTimeout: 250
  ReadTimeout: 2000

spring:
  profiles:
    active: development
---
spring:
  profiles: development
---
spring:
  profiles: docker
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
