message: Hello World!!!

server:
  port: ${PORT:8000}

spring:
  profiles:
    active: development
---
spring:
  profiles: development
---
spring:
  profiles: docker
  jpa:
    database: MYSQL
    generate-ddl: true
  datasource:
    url: jdbc:mysql://mysql:3306/dev
    username: root
    password: dbpass
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false
