message: Hello World!!!

server:
  port: ${PORT:8000}

spring.cloud.stream.bindings.input:
  # define the destination to which the input MessageChannel should be bound
  destination: reservations

  # ensures 1 node in a group gets message (point-to-point, not a broadcast)
  group: reservations

  # ensure that the Q is durable
  input.durableSubscription: true

spring:
  profiles:
    active: development
---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: root
    password: dbpass
    initialize: true
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql:3306/dev
    username: root
    password: dbpass
    initialize: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false
